# Generated by Django 3.1.2 on 2020-12-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_no', models.AutoField(primary_key=True, serialize=False)),
                ('ins_dt', models.DateTimeField(blank=True, null=True)),
                ('ins_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upd_dt', models.DateTimeField(blank=True, null=True)),
                ('upd_id', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('business_burden_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('coupon_issue_type_cd', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_state_cd', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_type_cd', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_apply_type_cd', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('deal_apply_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('discount_dup_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('down_show_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('issue_end_dt', models.DateTimeField()),
                ('issue_start_dt', models.DateTimeField()),
                ('max_dc_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_issue_qty', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('max_mem_issue_qty', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('mem_issue_basis_cd', models.CharField(blank=True, max_length=100, null=True)),
                ('min_order_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('single_apply_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('term_days', models.IntegerField(blank=True, null=True)),
                ('term_end_dt', models.DateTimeField(blank=True, null=True)),
                ('term_start_dt', models.DateTimeField(blank=True, null=True)),
                ('term_type_cd', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sps_coupon',
                'managed': False,
            },
        ),
    ]
