# Generated by Django 3.1.4 on 2021-01-07 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms', '0001_initial'),
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.product'),
        ),
        migrations.AddField(
            model_name='exhibitoffshop',
            name='exhibit_no',
            field=models.ForeignKey(db_column='exhibit_no', on_delete=django.db.models.deletion.DO_NOTHING, to='dms.exhibit'),
        ),
        migrations.AddField(
            model_name='exhibitlang',
            name='exhibit_no',
            field=models.ForeignKey(db_column='exhibit_no', on_delete=django.db.models.deletion.DO_NOTHING, to='dms.exhibit'),
        ),
        migrations.AddField(
            model_name='exhibitgroup',
            name='exhibit_no',
            field=models.ForeignKey(db_column='exhibit_no', on_delete=django.db.models.deletion.DO_NOTHING, to='dms.exhibit'),
        ),
        migrations.AddField(
            model_name='exhibitdisplaycategory',
            name='display_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dms.displaycategory'),
        ),
        migrations.AddField(
            model_name='exhibitdisplaycategory',
            name='exhibit_no',
            field=models.ForeignKey(db_column='exhibit_no', on_delete=django.db.models.deletion.DO_NOTHING, to='dms.exhibit'),
        ),
        migrations.AddField(
            model_name='exhibitcoupon',
            name='exhibit_no',
            field=models.ForeignKey(db_column='exhibit_no', on_delete=django.db.models.deletion.DO_NOTHING, to='dms.exhibit'),
        ),
        migrations.AddField(
            model_name='exhibitbrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.brand'),
        ),
        migrations.AddField(
            model_name='exhibitbrand',
            name='exhibit_no',
            field=models.ForeignKey(db_column='exhibit_no', on_delete=django.db.models.deletion.DO_NOTHING, to='dms.exhibit'),
        ),
        migrations.AddField(
            model_name='displayitemlang',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dms.displayitem'),
        ),
        migrations.AddField(
            model_name='displayitem',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dms.display'),
        ),
        migrations.AddField(
            model_name='displaycategoryproduct',
            name='display_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dms.displaycategory'),
        ),
        migrations.AddField(
            model_name='displaycategoryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.product'),
        ),
        migrations.AddField(
            model_name='displaycategorylang',
            name='display_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dms.displaycategory'),
        ),
        migrations.AddField(
            model_name='displaycategory',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dms.template'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.product'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogimg',
            unique_together={('catalog_img_no', 'catalog_no')},
        ),
        migrations.AlterUniqueTogether(
            name='templatedisplay',
            unique_together={('display', 'template')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitproduct',
            unique_together={('exhibit_no', 'group_no', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitoffshop',
            unique_together={('exhibit_no', 'offshop_no')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitlang',
            unique_together={('exhibit_no', 'lang_id')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitgroup',
            unique_together={('exhibit_no', 'group_no')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitdisplaycategory',
            unique_together={('display_category', 'exhibit_no')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitcoupon',
            unique_together={('coupon_no', 'exhibit_no')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitbrand',
            unique_together={('brand', 'exhibit_no')},
        ),
        migrations.AlterUniqueTogether(
            name='displayitemlang',
            unique_together={('display', 'display_item_no', 'lang_id')},
        ),
        migrations.AlterUniqueTogether(
            name='displayitem',
            unique_together={('display', 'display_item_no')},
        ),
        migrations.AlterUniqueTogether(
            name='displaycategoryproduct',
            unique_together={('display_category', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='displaycategorylang',
            unique_together={('display_category', 'lang_id')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogproduct',
            unique_together={('catalog_img_no', 'catalog_no', 'product')},
        ),
    ]
