# Generated by Django 3.1.4 on 2021-01-07 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms', '0001_initial'),
        ('ccs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offshopbrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.brand'),
        ),
        migrations.AddField(
            model_name='offshopbrand',
            name='offshop_no',
            field=models.ForeignKey(db_column='offshop_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.offshop'),
        ),
        migrations.AddField(
            model_name='offshop',
            name='business_no',
            field=models.ForeignKey(blank=True, db_column='business_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.business'),
        ),
        migrations.AddField(
            model_name='noticeproduct',
            name='notice_no',
            field=models.ForeignKey(db_column='notice_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.notice'),
        ),
        migrations.AddField(
            model_name='noticeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.product'),
        ),
        migrations.AddField(
            model_name='noticelang',
            name='notice_no',
            field=models.ForeignKey(db_column='notice_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.notice'),
        ),
        migrations.AddField(
            model_name='noticebrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.brand'),
        ),
        migrations.AddField(
            model_name='noticebrand',
            name='notice_no',
            field=models.ForeignKey(db_column='notice_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.notice'),
        ),
        migrations.AddField(
            model_name='notice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.store'),
        ),
        migrations.AddField(
            model_name='menulang',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.menu'),
        ),
        migrations.AddField(
            model_name='menugrouplang',
            name='menu_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.menugroup'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.menugroup'),
        ),
        migrations.AddField(
            model_name='inquirytransfer',
            name='inquiry_no',
            field=models.ForeignKey(blank=True, db_column='inquiry_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.inquiry'),
        ),
        migrations.AddField(
            model_name='inquirytransfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.user'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='business_no',
            field=models.ForeignKey(blank=True, db_column='business_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.business'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.store'),
        ),
        migrations.AddField(
            model_name='functionurl',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.function'),
        ),
        migrations.AddField(
            model_name='functionlang',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.function'),
        ),
        migrations.AddField(
            model_name='function',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.menu'),
        ),
        migrations.AddField(
            model_name='faqlang',
            name='faq_no',
            field=models.ForeignKey(db_column='faq_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.faq'),
        ),
        migrations.AddField(
            model_name='faq',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.store'),
        ),
        migrations.AddField(
            model_name='excproduct',
            name='apply_no',
            field=models.ForeignKey(db_column='apply_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.apply'),
        ),
        migrations.AddField(
            model_name='excproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.product'),
        ),
        migrations.AddField(
            model_name='deliverypolicy',
            name='business_no',
            field=models.ForeignKey(blank=True, db_column='business_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.business'),
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='delivery_policy_no',
            field=models.ForeignKey(db_column='delivery_policy_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.deliverypolicy'),
        ),
        migrations.AddField(
            model_name='controlmembertype',
            name='control_no',
            field=models.ForeignKey(db_column='control_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.control'),
        ),
        migrations.AddField(
            model_name='controlmembergrade',
            name='control_no',
            field=models.ForeignKey(db_column='control_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.control'),
        ),
        migrations.AddField(
            model_name='controldevice',
            name='control_no',
            field=models.ForeignKey(db_column='control_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.control'),
        ),
        migrations.AddField(
            model_name='controlchannel',
            name='channel_no',
            field=models.ForeignKey(db_column='channel_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.channel'),
        ),
        migrations.AddField(
            model_name='controlchannel',
            name='control_no',
            field=models.ForeignKey(db_column='control_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.control'),
        ),
        migrations.AddField(
            model_name='commission',
            name='business_no',
            field=models.ForeignKey(db_column='business_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.business'),
        ),
        migrations.AddField(
            model_name='codelang',
            name='cd_fk',
            field=models.ForeignObject(from_fields=['cd', 'cd_group_cd'], on_delete=django.db.models.deletion.CASCADE, to='ccs.code', to_fields=['cd', 'cd_group_cd']),
        ),
        migrations.AddField(
            model_name='codegrouplang',
            name='cd_group_cd',
            field=models.ForeignKey(db_column='cd_group_cd', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.codegroup'),
        ),
        migrations.AddField(
            model_name='code',
            name='cd_group_cd',
            field=models.ForeignKey(db_column='cd_group_cd', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.codegroup'),
        ),
        migrations.AddField(
            model_name='channel',
            name='business_no',
            field=models.ForeignKey(blank=True, db_column='business_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.business'),
        ),
        migrations.AddField(
            model_name='channel',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.store'),
        ),
        migrations.AddField(
            model_name='businesspolicy',
            name='business_no',
            field=models.ForeignKey(db_column='business_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.business'),
        ),
        migrations.AddField(
            model_name='businesspolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.policy'),
        ),
        migrations.AddField(
            model_name='businesspolicy',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.store'),
        ),
        migrations.AddField(
            model_name='businessinquirycategory',
            name='business_inquiry_no',
            field=models.ForeignKey(db_column='business_inquiry_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.businessinquiry'),
        ),
        migrations.AddField(
            model_name='businessinquiry',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.store'),
        ),
        migrations.AddField(
            model_name='businessholiday',
            name='business_no',
            field=models.ForeignKey(db_column='business_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.business'),
        ),
        migrations.AddField(
            model_name='business',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.store'),
        ),
        migrations.AlterUniqueTogether(
            name='batchlog',
            unique_together={('batch_id', 'batch_log_no')},
        ),
        migrations.AddField(
            model_name='applytarget',
            name='apply_no',
            field=models.ForeignKey(db_column='apply_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.apply'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliatedbinout',
            unique_together={('business_no', 'io_div')},
        ),
        migrations.AddField(
            model_name='accessmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.menu'),
        ),
        migrations.AddField(
            model_name='accessmenu',
            name='role_no',
            field=models.ForeignKey(db_column='role_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.role'),
        ),
        migrations.AddField(
            model_name='accessfunction',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.function'),
        ),
        migrations.AddField(
            model_name='accessfunction',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccs.accessmenu'),
        ),
        migrations.AlterUniqueTogether(
            name='storepolicy',
            unique_together={('policy', 'store', 'storepolicy_id')},
        ),
        migrations.AlterUniqueTogether(
            name='storelanguage',
            unique_together={('lang_id', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='storelang',
            unique_together={('lang_id', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='storecountry',
            unique_together={('country_id', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='popupurl',
            unique_together={('popup_no', 'popup_url_no')},
        ),
        migrations.AlterUniqueTogether(
            name='policylang',
            unique_together={('lang_id', 'policy')},
        ),
        migrations.AlterUniqueTogether(
            name='offshoplang',
            unique_together={('lang_id', 'offshop_no')},
        ),
        migrations.AlterUniqueTogether(
            name='offshopholiday',
            unique_together={('holiday', 'offshop_no')},
        ),
        migrations.AlterUniqueTogether(
            name='offshopbrand',
            unique_together={('brand', 'offshop_no')},
        ),
        migrations.AlterUniqueTogether(
            name='noticeproduct',
            unique_together={('notice_no', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='noticelang',
            unique_together={('lang_id', 'notice_no')},
        ),
        migrations.AlterUniqueTogether(
            name='noticebrand',
            unique_together={('brand', 'notice_no')},
        ),
        migrations.AlterUniqueTogether(
            name='menulang',
            unique_together={('lang_id', 'menu')},
        ),
        migrations.AlterUniqueTogether(
            name='menugrouplang',
            unique_together={('lang_id', 'menu_group')},
        ),
        migrations.AlterUniqueTogether(
            name='functionurl',
            unique_together={('function', 'menu_id', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='functionlang',
            unique_together={('function', 'lang_id', 'menu_id')},
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('function_id', 'menu')},
        ),
        migrations.AlterUniqueTogether(
            name='faqlang',
            unique_together={('faq_no', 'lang_id')},
        ),
        migrations.AlterUniqueTogether(
            name='excproduct',
            unique_together={('apply_no', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryfee',
            unique_together={('delivery_policy_no', 'zip_cd')},
        ),
        migrations.AlterUniqueTogether(
            name='controlmembertype',
            unique_together={('control_no', 'member_type_cd')},
        ),
        migrations.AlterUniqueTogether(
            name='controlmembergrade',
            unique_together={('control_no', 'member_grade_cd')},
        ),
        migrations.AlterUniqueTogether(
            name='controldevice',
            unique_together={('control_no', 'device_type_cd')},
        ),
        migrations.AlterUniqueTogether(
            name='controlchannel',
            unique_together={('channel_no', 'control_no')},
        ),
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together={('business_no', 'commission_no')},
        ),
        migrations.AlterUniqueTogether(
            name='codelang',
            unique_together={('cd', 'cd_group_cd', 'lang_id')},
        ),
        migrations.AlterUniqueTogether(
            name='codegrouplang',
            unique_together={('cd_group_cd', 'lang_id')},
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together={('cd', 'cd_group_cd')},
        ),
        migrations.AlterUniqueTogether(
            name='businesspolicy',
            unique_together={('policy', 'business_no', 'store', 'storepolicy_id')},
        ),
        migrations.AlterUniqueTogether(
            name='businessinquirycategory',
            unique_together={('business_inquiry_no', 'category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='businessholiday',
            unique_together={('business_no', 'holiday')},
        ),
        migrations.AlterUniqueTogether(
            name='applytarget',
            unique_together={('apply_no', 'target_id')},
        ),
        migrations.AlterUniqueTogether(
            name='accessmenu',
            unique_together={('menu', 'role_no')},
        ),
        migrations.AlterUniqueTogether(
            name='accessfunction',
            unique_together={('function', 'menu', 'role_no')},
        ),
    ]
